DROP TABLE IF EXISTS REQUEST;
DROP TABLE IF EXISTS WORDS_REQUEST_TABLE;

CREATE TABLE REQUEST(
    id INT AUTO_INCREMENT PRIMARY KEY,
    input_text TEXT NOT NULL,
    output_text TEXT NOT NULL,
    language_from VARCHAR(10) NOT NULL,
    language_to VARCHAR(10) NOT NULL,
    ip VARCHAR(15) NOT NULL,
    created TIMESTAMP DEFAULT now()
);

CREATE TABLE WORDS_REQUEST_TABLE(
    id INT AUTO_INCREMENT PRIMARY KEY,
    input_word VARCHAR(50) NOT NULL,
    output_word VARCHAR(50) NOT NULL,
    request_id INT REFERENCES REQUEST(id)
);